name: advanced_flutter_projexct
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependency_overrides:
  flutter_svg: 1.1.6

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_indicator: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Black.ttf
      - asset: assets/fonts/Poppins-BlackItalic.ttf
        weight: 900
      - asset: assets/fonts/Poppins-ExtraBold.ttf
      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
      - asset: assets/fonts/Poppins-SemiBold.ttf
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Medium.ttf
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Light.ttf
      - asset: assets/fonts/Poppins-LightItalic.ttf
        weight: 300
      - asset: assets/fonts/Poppins-ExtraLight.ttf
      - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        weight: 200

